apiVersion: v1
kind: Service
metadata:
  name: transactionapi
spec:
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: transactionapi
    tier: backend
