apiVersion: apps/v1
kind: Deployment
metadata:
  name: synpulse-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: node
        image: ansoncheungbk/synpulse-test:v1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: docker-hub