apiVersion: v1
kind: Service
metadata:
  name: test-server
spec:
  selector:
    app: test-server
  ports:
    - protocol: TCP
      nodePort: 32675
      port: 8080
      targetPort: 8080
  type: LoadBalancer