apiVersion: v1
kind: Service
metadata:
  name: synpulse-test
spec:
  ports:
    - name: app
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: synpulse-test
    tier: backend
